### ISSUE TITLE
troubleshoot GH actions

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#882]
The GH actions checks are failing, timing out on vignette building. I suspect this is probably because of some kind of overthreading/parallelization gone wild.  Also worth updating the YAML to the current version of the r-check action (or whatever it is) to address a bunch of deprecation warnings, update check platform to the latest LTS Ubuntu (22.04), etc etc..

**Comment by bbolker** [comment]
Tried to work on this some but failed.  Updated to Ubuntu 22.04 but that may have been a mistake, having library problems with `libicu` ...

**Comment by bbolker** [comment]
CRAN version of `remotes::system_dependencies()` doesn't support Ubuntu 22.04 (this fails silently in the actions, so dependencies don't get installed).  Could try installing github version of `remotes`; for the time being I'm attempting to revert to 20.04.

**Comment by bbolker** [comment]
Still not fixed. I don't know what's going on 

- symptoms are that the checking stage, and I think in particular the vignette-building/checking stage, takes forever (until run gets stopped after 45 minutes or so). Right now GH Actions isn't even showing me the interim output from the check, not sure why (I may be able to see it once it stops)
- I am **guessing** that this may be due to overparallelization, but only because that's been a problem before. However, I don't think it's popped up on any other [more convenient to debug] platforms ...

Any ideas would be welcome.

**Comment by larmarange** [comment]
Up

**Comment by larmarange** [comment]
It seems that GitHub actions fail to install glmmTMB on Ubuntu only (but it works properly on Windows and MacOS).

**Comment by larmarange** [comment]
It seems that the failure occurred only when all packages had to be installed.
Deactivating `glmmTMB` with `?ignore` to install and cache the other packages and then reactivating `glmmTMB` solved the issue.

**Comment by bbolker** [comment]
This is great.  Can you expand on/clarify how to perform those steps? 

(I also wonder if there's a github actions recipe for using the `r2u` repository to install packages as binaries ... ??)

**Comment by larmarange** [comment]
In the YAML of a github action, I have change these lines:

```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
```

by  

```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, glmmTMB=?ignore
          needs: check
```
